package com.kh.mini_project.common;

public class MemberQuery {
    public static final String INSERT_QUERY = "" +
            "INSERT INTO MEMBER(MEMBER_NUM, ID, PASSWORD, EMAIL, NICKNAME, REGISTRATION_DATE) " +
            "VALUES(SEQ_MEMBER.NEXTVAL, ?, ?, ?, ?, ?)";
    public static final String SELECT_COUNT_BY_FIELD_AND_VALUE_QUERY = "SELECT COUNT(*) FROM MEMBER WHERE %s=?";
    public static final String SELECT_COUNT_BY_ID_AND_PASSWORD_QUERY = "SELECT COUNT(*) FROM MEMBER WHERE ID=? AND PASSWORD=?";
    public static final String SELECT_MEMBER_NUM_BY_ID_QUERY = "SELECT MEMBER_NUM FROM MEMBER WHERE ID=?";

    // 참조 데이터 삭제 쿼리
    public static final String DELETE_DIARY_TAG_BY_MEMBER_NUM = "DELETE FROM DIARY_TAG WHERE DIARY_NUM IN (SELECT DIARY_NUM FROM DIARY WHERE MEMBER_NUM = ?)";
    public static final String DELETE_CODING_DIARY_ENTRY_BY_MEMBER_NUM = "DELETE FROM CODING_DIARY_ENTRY WHERE CODING_DIARY_NUM IN (SELECT CODING_DIARY_NUM FROM CODING_DIARY WHERE DIARY_NUM IN (SELECT DIARY_NUM FROM DIARY WHERE MEMBER_NUM = ?))";
    public static final String DELETE_CODING_DIARY_BY_MEMBER_NUM = "DELETE FROM CODING_DIARY WHERE DIARY_NUM IN (SELECT DIARY_NUM FROM DIARY WHERE MEMBER_NUM = ?)";
    public static final String DELETE_DIARY_BY_MEMBER_NUM = "DELETE FROM DIARY WHERE MEMBER_NUM = ?";
    public static final String DELETE_NOTIFICATION_BY_MEMBER_NUM = "DELETE FROM RECEIVED_NOTIFICATION WHERE MEMBER_NUM = ?";
    public static final String DELETE_SCHEDULE_NOTIFICATIONS_BY_MEMBER_NUM = "DELETE FROM NOTIFICATION WHERE SCHEDULE_NUM IN (SELECT SCHEDULE_NUM FROM SCHEDULE WHERE MEMBER_NUM = ?)";
    public static final String DELETE_SCHEDULE_BY_MEMBER_NUM = "DELETE FROM SCHEDULE WHERE MEMBER_NUM = ?";
    public static final String DELETE_DIARY_SETTINGS_BY_MEMBER_NUM = "DELETE FROM DIARY_SETTING WHERE MEMBER_NUM = ?";

    // 회원 삭제 쿼리
    public static final String DELETE_MEMBER_BY_MEMBER_NUM = "DELETE FROM MEMBER WHERE MEMBER_NUM = ?";
}
